application:
  enabled: true
migration:
  enabled: true
databaseProvisioning:
  enabled: true
  database: affine
  admin:
    secretName: db-affine-bootstrap
    hostKey: pgbouncer-host
    portKey: pgbouncer-port
    usernameKey: user
    passwordKey: password
  application:
    usernameKey: POSTGRES_USERNAME
    passwordKey: POSTGRES_PASSWORD
prerequisites:
  enabled: true
  database:
    mode: everest
    name: db-affine
    namespace: prod
    userSecretName: db-affine-bootstrap
  redis:
    enabled: true
secrets:
  mode: existing
  database:
    name: affine-database
  redis:
    name: affine-redis
routing:
  mode: none
