{{- if .Values.application.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "affine.fullname" . }}-config
  labels: {{- include "affine.labels" . | nindent 4 }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
data:
  config.json: |-
    {"$schema":"https://github.com/toeverything/AFFiNE/releases/download/v{{ .Chart.AppVersion }}/config.schema.json","server":{"name":"{{ .Values.config.serverName }}","externalUrl":"{{ .Values.config.externalUrl }}"}}
{{- end }}
