{{- if and (eq .Values.secrets.mode "create") .Values.prerequisites.enabled (ne .Values.prerequisites.database.mode "external") (not (lookup "v1" "Secret" (include "affine.prerequisiteDatabaseNamespace" .) (include "affine.databaseBootstrapSecretName" .))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.databaseBootstrapSecretName" . }}
  namespace: {{ include "affine.prerequisiteDatabaseNamespace" . }}
  labels: {{- include "affine.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  user: {{ .Values.prerequisites.database.secret.username | quote }}
  password: {{ .Values.prerequisites.database.secret.password | quote }}
{{- end }}
