{{- if and .Values.prerequisites.enabled (eq .Values.prerequisites.database.mode "everest") }}
apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: {{ .Values.prerequisites.database.name }}
  namespace: {{ .Values.prerequisites.database.namespace }}
  annotations: {argocd.argoproj.io/sync-wave: "-2"}
spec:
  engine:
    type: postgresql
    version: {{ .Values.prerequisites.database.version | quote }}
    replicas: {{ .Values.prerequisites.database.replicas }}
    resources:
      cpu: "1"
      memory: 2G
    storage:
      class: {{ .Values.prerequisites.database.storageClass }}
      size: {{ .Values.prerequisites.database.storageSize }}
    userSecretsName: {{ include "affine.databaseBootstrapSecretName" . }}
  proxy:
    type: pgbouncer
    replicas: 1
    expose:
      type: ClusterIP
    resources:
      cpu: 500m
      memory: 512Mi
{{- end }}
