{{- if and .Values.prerequisites.enabled (eq .Values.secrets.mode "create") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prerequisites.database.userSecretName }}
  namespace: {{ .Values.prerequisites.database.namespace }}
  annotations: {argocd.argoproj.io/sync-wave: "-3"}
type: Opaque
stringData:
  user: {{ required "secrets.database.data.POSTGRES_USERNAME is required when creating prerequisites" .Values.secrets.database.data.POSTGRES_USERNAME | quote }}
  password: {{ required "secrets.database.data.POSTGRES_PASSWORD is required when creating prerequisites" .Values.secrets.database.data.POSTGRES_PASSWORD | quote }}
{{- end }}
