{{- include "affine.validateSecrets" . }}
{{- if eq .Values.secrets.mode "create" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.databaseSecretName" . }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.database.data.DATABASE_URL is required" .Values.secrets.database.data.DATABASE_URL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.redisSecretName" . }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
type: Opaque
stringData:
  REDIS_SERVER_HOST: {{ .Values.secrets.redis.data.REDIS_SERVER_HOST | quote }}
  REDIS_SERVER_PORT: {{ .Values.secrets.redis.data.REDIS_SERVER_PORT | quote }}
  REDIS_SERVER_USERNAME: {{ .Values.secrets.redis.data.REDIS_SERVER_USERNAME | quote }}
  REDIS_SERVER_PASSWORD: {{ .Values.secrets.redis.data.REDIS_SERVER_PASSWORD | quote }}
  REDIS_SERVER_DATABASE: {{ .Values.secrets.redis.data.REDIS_SERVER_DATABASE | quote }}
{{- end }}
