{{- if eq .Values.secrets.mode "create" }}
{{- if or .Values.application.enabled .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.databaseSecretName" . }}
  namespace: {{ include "affine.databaseSecretNamespace" . }}
  labels: {{- include "affine.labels" . | nindent 4 }}
  annotations: {argocd.argoproj.io/sync-wave: "-2"}
type: Opaque
stringData:
  {{- with .Values.secrets.database.data.POSTGRES_USERNAME }}
  POSTGRES_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.database.data.POSTGRES_PASSWORD }}
  POSTGRES_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.database.data.DATABASE_URL }}
  DATABASE_URL: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if or .Values.application.enabled .Values.migration.enabled .Values.prerequisites.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.redisSecretName" . }}
  namespace: {{ include "affine.redisSecretNamespace" . }}
  labels: {{- include "affine.labels" . | nindent 4 }}
  annotations: {argocd.argoproj.io/sync-wave: "-2"}
type: Opaque
stringData:
  REDIS_SERVER_HOST: {{ .Values.secrets.redis.data.REDIS_SERVER_HOST | quote }}
  REDIS_SERVER_PORT: {{ .Values.secrets.redis.data.REDIS_SERVER_PORT | quote }}
  REDIS_SERVER_USERNAME: {{ .Values.secrets.redis.data.REDIS_SERVER_USERNAME | quote }}
  REDIS_SERVER_PASSWORD: {{ .Values.secrets.redis.data.REDIS_SERVER_PASSWORD | quote }}
  REDIS_SERVER_DATABASE: {{ .Values.secrets.redis.data.REDIS_SERVER_DATABASE | quote }}
{{- end }}
{{- end }}
