{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "affine.serviceAccountName" . }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
automountServiceAccountToken: false
{{- end }}
