{{- if and .Values.serviceAccount.create (or .Values.application.enabled .Values.migration.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "affine.serviceAccountName" . }}
  labels: {{- include "affine.labels" . | nindent 4 }}
  annotations: {argocd.argoproj.io/sync-wave: "0"}
automountServiceAccountToken: false
{{- end }}
