{{- if .Values.application.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "affine.fullname" . }}
  labels: {{- include "affine.labels" . | nindent 4 }}
  annotations: {argocd.argoproj.io/sync-wave: "3"}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "affine.selectorLabels" . | nindent 4 }}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]
{{- end }}
